# Generated by Django 6.0 on 2025-12-27 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionperfil', models.CharField(max_length=50)),
                ('perfilactivo', models.BooleanField(default=True)),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('lugarnacimiento', models.CharField(max_length=60)),
                ('fechanacimiento', models.DateField()),
                ('numerocedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('estadocivil', models.CharField(max_length=50)),
                ('licenciaconducir', models.CharField(max_length=6)),
                ('telefonoconvencional', models.CharField(max_length=15)),
                ('telefonofijo', models.CharField(max_length=15)),
                ('direcciontrabajo', models.CharField(max_length=50)),
                ('direcciondomiciliaria', models.CharField(max_length=50)),
                ('sitioweb', models.CharField(max_length=60)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
            ],
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('idcursorealizado', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(max_length=100)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('totalhoras', models.IntegerField()),
                ('descripcioncurso', models.CharField(max_length=100)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(max_length=100)),
                ('telefonocontactoauspicia', models.CharField(max_length=60)),
                ('emailempresapatrocinadora', models.EmailField(max_length=60)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cv.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('idexperiencialaboral', models.AutoField(primary_key=True, serialize=False)),
                ('cargodesempenado', models.CharField(max_length=100)),
                ('nombrempresa', models.CharField(max_length=50)),
                ('lugarempresa', models.CharField(max_length=50)),
                ('emailempresa', models.EmailField(max_length=100)),
                ('sitiowebempresa', models.CharField(max_length=100)),
                ('nombrecontactoempresarial', models.CharField(max_length=100)),
                ('telefonocontactoempresarial', models.CharField(max_length=60)),
                ('fechainiciogestion', models.DateField()),
                ('fechafingestion', models.DateField(blank=True, null=True)),
                ('descripcionfunciones', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='cv.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('idproductoacademico', models.AutoField(primary_key=True, serialize=False)),
                ('nombrerecurso', models.CharField(max_length=100)),
                ('clasificador', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='cv.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('idproductoslaborales', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('fechaproducto', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='cv.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('idreconocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100)),
                ('fechareconocimiento', models.DateField()),
                ('descripcionreconocimiento', models.CharField(max_length=100)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(max_length=100)),
                ('telefonocontactoauspicia', models.CharField(max_length=60)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='cv.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('idventagarage', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_garage', to='cv.datospersonales')),
            ],
        ),
    ]
